### ISSUE TITLE
docker access denied error

### ISSUE THREAD

**Issue by krrishdholakia** [neuralmagic/deepsparse#1452]
**Describe the bug**
I'm trying to pull the docker image but hitting an access denied error 

**Expected behavior**
i would expect `docker pull ghcr.io/neuralmagic/deepsparse:1.5.1` to work

**Environment**
I'm on a mac. 

Running: 
`docker pull ghcr.io/neuralmagic/deepsparse:1.5.1`

**Comment by mgoin** [comment]
Hi @krrishdholakia that docker pull command works on my M1 MacBook. Any further context you can provide about your environment?
<img width="1043" alt="Screenshot 2023-12-04 at 5 34 40 PM" src="https://github.com/neuralmagic/deepsparse/assets/3195154/d6b93f3c-576b-47ff-a3c1-478c0c29e89c">

I did uncover an issue with the latest nightly docker though, so we will be looking into that:
```
➜  ~ docker pull ghcr.io/neuralmagic/deepsparse-nightly
Using default tag: latest
latest: Pulling from neuralmagic/deepsparse-nightly
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by krrishdholakia** [comment]
@mgoin i'm trying to get a local server running, so i can add support for it via litellm. How do i do that with the pip package? 

`pip install deepsparse-nightly`

```deepsparse.server \
  --task sentiment-analysis \
  --model_path zoo:nlp/sentiment_analysis/obert-base/pytorch/huggingface/sst2/pruned90_quant-none```

<img width="825" alt="Screenshot 2023-12-09 at 10 57 49 AM" src="https://github.com/neuralmagic/deepsparse/assets/17561003/9aadd52b-9327-4252-89b3-375083f801d9">

**Comment by krrishdholakia** [comment]
<img width="813" alt="Screenshot 2023-12-09 at 10 59 22 AM" src="https://github.com/neuralmagic/deepsparse/assets/17561003/00437d66-b2e6-4ef5-bbc3-4c8325b4f9b7">

**Comment by mgoin** [comment]
Hi @krrishdholakia what version of python do you have? We support python 3.8-3.11 as of 1.6 stable or nightly.

If you want to use the server and transformers, you need to install those extras - as in `pip install -U deepsparse-nightly[server,transformers]`. 

Here is a colab notebook as an example: https://colab.research.google.com/drive/1Ng10jwBLUs81SDzZLE9P8G-q8D2YyKeL?usp=sharing

**Comment by krrishdholakia** [comment]
thanks for the colab @mgoin i have 3.11 

<img width="562" alt="Screenshot 2023-12-09 at 12 11 18 PM" src="https://github.com/neuralmagic/deepsparse/assets/17561003/675756a4-092d-408f-8ae1-dece990fd6c3">

**Comment by krrishdholakia** [comment]
@mgoin any suggestions for how i can actually use / test the server from the colab, i was thinking about running it via ngrok, but not sure how i could wrap it. 
<img width="1289" alt="Screenshot 2023-12-09 at 12 13 11 PM" src="https://github.com/neuralmagic/deepsparse/assets/17561003/eaa7d349-dae5-4466-a7e2-3b2956a1e2bf">

**Comment by mgoin** [comment]
Hey @krrishdholakia I wouldn't recommend trying to host a server from colab since it isn't a supported flow from Google.

You should be able to run that notebook locally from your macbook since we have native ARM MacOS support in the deepsparse release, I just shared the colab as an example of an environment working without docker.

Please let me know if you need a docker image built for ARM, otherwise please go the `pip install -U deepsparse-nightly[server,llm]` route in your local python environment.

We have docker images ready if you are on an x86 machine - here is an example running on windows docker:

Server:
```
docker run -p 5543:5543 -it ghcr.io/neuralmagic/deepsparse-nightly:20231220 deepsparse.server --task text-generation --integration openai --model_path hf:mgoin/llama2.c-stories15M-ds
```
![Screenshot 2023-12-20 195557](https://github.com/neuralmagic/deepsparse/assets/3195154/b5251a85-777c-404d-9290-5b0d65539814)

Client:
```
curl http://localhost:5543/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer dummy" \
  -d '{
    "model": "hf:mgoin/llama2.c-stories15M-ds",
    "messages": "Once upon a time"
  }'
```
![Screenshot 2023-12-20 195611](https://github.com/neuralmagic/deepsparse/assets/3195154/ce09a7c1-e460-4361-8184-4a75341f1c1a)

**Comment by jeanniefinks** [comment]
Hi @krrishdholakia 
As some time has passed with no further updates, I am going to go ahead and close out this issue.
Please re-open if you want to continue the conversation.
Best, Jeannie / Neural Magic
