### ISSUE TITLE
Expected Acceleration

### ISSUE THREAD

**Issue by bensuucar** [neuralmagic/deepsparse#66]
What is the maximum expected acceleration from Deepsparse? (Assuming that the model is sparsified further with sparseml as well)

In the documentation here, achieving GPU-level performance on CPUs is promised, however in this article (Inducing and Exploiting Activation Sparsity for Fast Neural Network Inference), the maximum acceleration on top of cpu is stated as 2.5x. So it is 2.5 times faster than running on cpu which is not very close to gpu performance. 

Thanks!

**Comment by markurtz** [comment]
Hi @bensuucar, thank you for reaching out and bringing this up! We'll be sure to update our documentation to make all of this clearer. That paper specifically looked into the effects of activation sparsity on performance. There are a few other techniques we can use to sparsify models, such as pruning and quantization. The expected acceleration can vary quite a bit depending on the methods and architecture used, though, and a general rule of thumb for the different techniques is the following:
- Activation Sparsity with ReLU based network: 1.5-2.5x speedup
- Unstructured Pruning: 1.5-3x speedup
- Quantization: 2-4x speedup
- Block Pruning + Quantization: 4-7x speedup

To give some concrete examples, we achieved a 7x speedup on ResNet-50 using pruning + quantization. If you'd like to dive in more on that model, we [published a blog post](https://neuralmagic.com/blog/benchmark-resnet50-with-deepsparse/) to walk through the critical pieces and how to reproduce the results.

Additionally, we'll be pushing out results for quantizing and pruning YOLOv3 this week, and I'll provide the link to the blog post in a follow-up once that launches. We're seeing over a 5x speedup for pruning + quantization in comparison with other CPU implementations for those results. 

We have some techniques in the works that we'll launch into DeepSparse over the coming months that will improve these numbers even further, so let me know if you'd like to be added to our marketing list so you can stay up to date!

**Comment by bensuucar** [comment]
Hi @markurtz, 
Thank you for the detailed explanation! I'll definitely be following the progress there. 

The reason why I asked the acceleration is that currently when I compare inference speed of deepsparse with cpu inference for UNet model with mobilenet backbone on 2kx2k image, the cpu inference is faster than deepsparse. 

As you can see below, cpu inference is 5.7 sec while Neural Magic Inference is 7.9 sec. 
I was wondering why it is the case. 
Thanks!

CPU Time 5728.959736414254
DeepSparse Engine, Copyright 2021-present / Neuralmagic, Inc. version: 0.1.1 (4191ab46) (release) (optimized) (system=avx2, binary=avx2)
NM Inference Time 7954.058458097279

**Comment by markurtz** [comment]
@bensuucar, thanks for the additional info! It's interesting; that is not what we would expect. For dense models, we hope to at least match other base CPU implementations such as ONNX Runtime. MobileNet backbones we would expect to run much faster since they can be considered structurally sparse and use the memory optimizations in DeepSparse. 

Is there a sample model/architecture you could provide or point us at to test more on our side and find out what might be going wrong?

Additionally, we released our 0.2.0 version, which does have some performance fixes for the resize ops usually found in UNet models. Could you try and run on the latest release and see if there is any difference?

Running the benchmark script under the examples folder could help us debug and compare the ONNX Runtime vs. DeepSparse results.

Finally, logging functionality shipped with DeepSparse could be beneficial to turn on and review for us. If you have a chance, could you look through the docs [here](https://docs.neuralmagic.com/deepsparse/debugging-optimizing/diagnostics-debugging.html#enabling-logs-and-controlling-the-amount-of-logs-produced-by-the-deepsparse-engine) and try out the diagnostic logs so we can check what's reported?

Thanks,
Mark

**Comment by markurtz** [comment]
Readme has been updated now with more info on expected acceleration for sparsification algorithms. Let us know if there is more that would help for us to add!
