### ISSUE TITLE
How does the quantized op infered?

### ISSUE THREAD

**Issue by jinfagang** [neuralmagic/deepsparse#852]
Hello, just out of curiosity. How does the quantized int conv op infered? It wasn't supported in onnxruntime I think? Not even a 
standared onnx op.

How does it infered?
<img width="443" alt="图片" src="https://user-images.githubusercontent.com/21303438/210921448-bf2768b8-5d0c-4ce0-8e60-be72d1680f29.png">

**Comment by mgoin** [comment]
Hi @jinfagang thanks for the interest. [ConvInteger](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvInteger) has been officially supported since ONNX opset 10, which is when most other major quantization operators were introduced (QuantizeLinear, QLinearMatMul, etc). ConvInteger takes int8/uint8 inputs and accumulates into an int32 output. Combined with QDQ (QuantizeLinear and DequantizeLinear) allows for less total conversions needed in the network, improving performance.

**Comment by jinfagang** [comment]
@mgoin  Hi，thanks for reply.

If so, I have a further question, since the ops are standared onnx op, is that possible infer using onnxruntime for deepsparse output model?

If so, how to infer without deepsparse compile?

**Comment by mgoin** [comment]
@jinfagang Yes you can run the models in ONNXRuntime as you normally would, they are just ONNX models using standard operations within the specification. Since you have it pulled up in Netron, you must have the `.onnx` file locally and can give that to ONNXRuntime in the standard way.

If you are curious to benchmark the same ONNX between the engines, we do have a benchmarking command that can take an ONNX and parameters, with one of them being `--engine` to choose between DeepSparse or ONNXRuntime
i.e.
For DeepSparse: `deepsparse.benchmark model.onnx --engine deepsparse`
For ONNXRuntime: `deepsparse.benchmark model.onnx --engine onnxruntime`

**Comment by jinfagang** [comment]
@mgoin  Hi, thanks for clarification. 

The reason why I ask, it because I found most of  the time, the int8 quantized model actually runing slower than normal float in onnxruntime.  (altough the way I quantized is not deepsparse, but normally using QTQ), but they just slower.

So I wonder:

1. Have u guys actually tested the int8 model **indeed** faster? Any benchmark result in real?
2. what's the differences here between --engine deepsparse and onnxruntime? Did u guys have totally implementation on onnx op yourself?

**Comment by mgoin** [comment]
Yes we do see significant speedup for int8 quantized models - you can view our many graphs, blogs and MLPerf submission to see that we definitely make use of quantization and sparsity for our performance improvements. 

Some examples:
https://neuralmagic.com/blog/deploy-yolov5-with-neural-magics-deepsparse-for-gpu-class-performance-on-cpus/
https://neuralmagic.com/blog/bert-large-prune-once-for-distilbert-inference-performance/

DeepSparse is its own inference engine with new implementations of running onnx operations, specifically so you can see speedup from unstructured sparsity in models.

**Comment by mgoin** [comment]
Let me know if you have any other questions, thanks!
